### 1. Cloning stage
FROM alpine/git@sha256:d453f54c83320412aa89c391b076930bd8569bc1012285e8c68ce2d4435826a3 AS clone
WORKDIR /workspace/pagopa-posgw-transactions-handler

ARG POSGW_TRANSACTIONS_HANDLER_GIT_REF

RUN rm -rf * && \
    git clone https://github.com/pagopa/pagopa-posgw-transactions-handler.git . && \
    git checkout "${POSGW_TRANSACTIONS_HANDLER_GIT_REF}"

### 2. Native build stage (GraalVM native-image)
# version 25
FROM ghcr.io/graalvm/native-image-community@sha256:3c53c5900ce3c39b1293a0d0f3417d04d4b4f07752fd083c322bf9f37ed8de0a AS build-native

WORKDIR /workspace/pagopa-posgw-transactions-handler/

ARG REPO=/workspace/pagopa-posgw-transactions-handler

COPY --from=clone ${REPO}/ .

#build the native executable
RUN chmod +x ./gradlew
RUN ./gradlew nativeCompile -x test

### 3. Native run stage
# version :stable-20240701-slim
FROM debian@sha256:f8bbfa052db81e5b8ac12e4a1d8310a85d1509d4d0d5579148059c0e8b717d4e AS run-native

RUN addgroup --system user && adduser --ingroup user --system user
USER user:user

WORKDIR /app/

EXPOSE 8080

COPY --from=build-native /workspace/pagopa-posgw-transactions-handler/build/native/nativeCompile/pagopa-posgw-transactions-handler .

ENV OTEL_JAVA_GLOBAL_AUTOCONFIGURE_ENABLED=true

ENTRYPOINT ["./pagopa-posgw-transactions-handler"]
